/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Color;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import modelo.DadosVEspacial;
import service.ClockThread;
import modelo.CustomRenderer;

/**
 *
 * @author Quitério
 */
public class AtividadeVEspacial extends javax.swing.JPanel {

    /**
     * Creates new form AtividadeVEspacial
     */
    public AtividadeVEspacial() {
        initComponents();
        jDialogTesteVEspacial.setLocationRelativeTo(this);
        jDialogTesteVEspacial.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogTesteVEspacial = new javax.swing.JDialog();
        jTabbedPaneVEspacial = new javax.swing.JTabbedPane();
        jPanelInstrucoes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jLabelFig0 = new javax.swing.JLabel();
        jButtonInstrucoesSeguinte = new javax.swing.JButton();
        jPanelR0 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jLabelFig01 = new javax.swing.JLabel();
        jButtonIniciar = new javax.swing.JButton();
        jButtonInstrucoesAnterior = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();
        jPanelQ1 = new javax.swing.JPanel();
        jLabelP1A = new javax.swing.JLabel();
        jLabelP1B = new javax.swing.JLabel();
        jLabelP1C = new javax.swing.JLabel();
        jLabelP1D = new javax.swing.JLabel();
        jLabelP1E = new javax.swing.JLabel();
        jLabelP1 = new javax.swing.JLabel();
        jButtonQuestoesSeguinte = new javax.swing.JButton();
        jLabelTempo = new javax.swing.JLabel();
        jPanelResultados = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableResultadosVE = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabelOutResultadosVE = new javax.swing.JLabel();

        jDialogTesteVEspacial.setMinimumSize(new java.awt.Dimension(670, 420));

        jTextPane1.setEditable(false);
        jTextPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextPane1.setText("Neste teste deve imaginar que está a dobrar e desdobrar folhas de papel. Em cada um dos problemas existem figuras desenhadas à esquerda e figuras desenhadas à direita. As figuras da esquerda representam um quadrado de papel a ser dobrado. Na última figura é desenhado um pequeno circulo que representa onde o papel é perfurado em toda a sua espessura. Nas figuras da direita é mostrado o local dos orifícios quando o papel é desdobrado. Deve assinalar qual das figuras corresponde ao desdobrar correto da figura da esquerda.");
        jScrollPane1.setViewportView(jTextPane1);

        jTextPane2.setEditable(false);
        jTextPane2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextPane2.setText("Analise o exemplo seguinte:");
        jScrollPane2.setViewportView(jTextPane2);

        jLabelFig0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensVEspacial/Fig1.png"))); // NOI18N

        jButtonInstrucoesSeguinte.setText("Seguinte");
        jButtonInstrucoesSeguinte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInstrucoesSeguinteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInstrucoesLayout = new javax.swing.GroupLayout(jPanelInstrucoes);
        jPanelInstrucoes.setLayout(jPanelInstrucoesLayout);
        jPanelInstrucoesLayout.setHorizontalGroup(
            jPanelInstrucoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInstrucoesLayout.createSequentialGroup()
                .addGroup(jPanelInstrucoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInstrucoesLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanelInstrucoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFig0, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelInstrucoesLayout.createSequentialGroup()
                        .addGap(525, 525, 525)
                        .addComponent(jButtonInstrucoesSeguinte, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanelInstrucoesLayout.setVerticalGroup(
            jPanelInstrucoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInstrucoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelFig0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButtonInstrucoesSeguinte)
                .addGap(27, 27, 27))
        );

        jTabbedPaneVEspacial.addTab("Instruções", jPanelInstrucoes);

        jTextPane3.setEditable(false);
        jTextPane3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextPane3.setText("A resposta correta ao problema anterior é a figura C. ");
        jScrollPane5.setViewportView(jTextPane3);

        jTextPane4.setEditable(false);
        jTextPane4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextPane4.setText("As figuras seguintes mostram porque é que a escolha da figura C é a resposta correta.");
        jScrollPane6.setViewportView(jTextPane4);

        jLabelFig01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensVEspacial/Fig2.png"))); // NOI18N

        jButtonIniciar.setText("Iniciar Questionário");
        jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarActionPerformed(evt);
            }
        });

        jButtonInstrucoesAnterior.setText("Anterior");
        jButtonInstrucoesAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInstrucoesAnteriorActionPerformed(evt);
            }
        });

        jTextPane5.setEditable(false);
        jTextPane5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextPane5.setText("Tem 6 minutos para responder 20 Questões.");
        jScrollPane7.setViewportView(jTextPane5);

        javax.swing.GroupLayout jPanelR0Layout = new javax.swing.GroupLayout(jPanelR0);
        jPanelR0.setLayout(jPanelR0Layout);
        jPanelR0Layout.setHorizontalGroup(
            jPanelR0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelR0Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelR0Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelR0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelR0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelR0Layout.createSequentialGroup()
                            .addComponent(jButtonInstrucoesAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(21, 21, 21))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelR0Layout.createSequentialGroup()
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(jPanelR0Layout.createSequentialGroup()
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelR0Layout.createSequentialGroup()
                        .addComponent(jLabelFig01)
                        .addGap(101, 101, 101))))
        );
        jPanelR0Layout.setVerticalGroup(
            jPanelR0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelR0Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelFig01, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanelR0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIniciar)
                    .addComponent(jButtonInstrucoesAnterior))
                .addGap(31, 31, 31))
        );

        jTabbedPaneVEspacial.addTab("Resposta 0", jPanelR0);

        jPanelQ1.setLayout(null);

        jLabelP1A.setToolTipText("");
        jLabelP1A.setName(""); // NOI18N
        jPanelQ1.add(jLabelP1A);
        jLabelP1A.setBounds(340, 120, 50, 100);
        jPanelQ1.add(jLabelP1B);
        jLabelP1B.setBounds(390, 120, 50, 100);

        jLabelP1C.setToolTipText("A");
        jPanelQ1.add(jLabelP1C);
        jLabelP1C.setBounds(440, 120, 50, 100);
        jPanelQ1.add(jLabelP1D);
        jLabelP1D.setBounds(490, 120, 50, 100);
        jPanelQ1.add(jLabelP1E);
        jLabelP1E.setBounds(540, 120, 50, 100);
        jPanelQ1.add(jLabelP1);
        jLabelP1.setBounds(105, 110, 570, 120);

        jButtonQuestoesSeguinte.setText("Seguinte");
        jButtonQuestoesSeguinte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuestoesSeguinteActionPerformed(evt);
            }
        });
        jPanelQ1.add(jButtonQuestoesSeguinte);
        jButtonQuestoesSeguinte.setBounds(523, 320, 100, 23);

        jLabelTempo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelTempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTempo.setText("00:00");
        jLabelTempo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelQ1.add(jLabelTempo);
        jLabelTempo.setBounds(540, 20, 90, 33);

        jTabbedPaneVEspacial.addTab("Q01", jPanelQ1);

        javax.swing.GroupLayout jDialogTesteVEspacialLayout = new javax.swing.GroupLayout(jDialogTesteVEspacial.getContentPane());
        jDialogTesteVEspacial.getContentPane().setLayout(jDialogTesteVEspacialLayout);
        jDialogTesteVEspacialLayout.setHorizontalGroup(
            jDialogTesteVEspacialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneVEspacial)
        );
        jDialogTesteVEspacialLayout.setVerticalGroup(
            jDialogTesteVEspacialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneVEspacial)
        );

        jTableResultadosVE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Questão", "Solução", "Resposta", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableResultadosVE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Resultados");

        jLabelOutResultadosVE.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelOutResultadosVE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOutResultadosVE.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanelResultadosLayout = new javax.swing.GroupLayout(jPanelResultados);
        jPanelResultados.setLayout(jPanelResultadosLayout);
        jPanelResultadosLayout.setHorizontalGroup(
            jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelResultadosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelOutResultadosVE, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
            .addGroup(jPanelResultadosLayout.createSequentialGroup()
                .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelResultadosLayout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel1))
                    .addGroup(jPanelResultadosLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanelResultadosLayout.setVerticalGroup(
            jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelOutResultadosVE, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInstrucoesSeguinteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInstrucoesSeguinteActionPerformed
        int index = jTabbedPaneVEspacial.getSelectedIndex();
        jTabbedPaneVEspacial.setSelectedIndex(index + 1);
        jTabbedPaneVEspacial.repaint();
    }//GEN-LAST:event_jButtonInstrucoesSeguinteActionPerformed

    private void jButtonInstrucoesAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInstrucoesAnteriorActionPerformed
        int index = jTabbedPaneVEspacial.getSelectedIndex();
        jTabbedPaneVEspacial.setSelectedIndex(index - 1);
        jTabbedPaneVEspacial.repaint();
    }//GEN-LAST:event_jButtonInstrucoesAnteriorActionPerformed

  

    private void jLabelMouseClicked(java.awt.event.MouseEvent evt, char op) {
        String name = "escolha";
        if (labelEscolha[op - 'A'].getName().equals(name)) {
            labelEscolha[op - 'A'].setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
            labelEscolha[op - 'A'].setName("");
            escolha = 'X';
        } else {
            for (int i = 0; i < 5; i++) {
                labelEscolha[i].setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
                labelEscolha[i].setName("");
            }
            labelEscolha[op - 'A'].setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0), 5));
            labelEscolha[op - 'A'].setName("escolha");
            escolha = op;
        }
    }


    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed
        carregaImagensVEspacial();
        labelEscolha[0] = jLabelP1A;
        labelEscolha[1] = jLabelP1B;
        labelEscolha[2] = jLabelP1C;
        labelEscolha[3] = jLabelP1D;
        labelEscolha[4] = jLabelP1E;
        criarQuestoesVEspacial(questaoAtual);
        jTabbedPaneVEspacial.setSelectedIndex(2);
        jTabbedPaneVEspacial.repaint();
        respostas = new char[20];
        clockThread = new Thread(){
             public void run(){
                 runClock(360);
             }
        };
        clockThread.start();
    }//GEN-LAST:event_jButtonIniciarActionPerformed

    private void runClock(int time) {
        try {
            while ((runFlag) && (time >= 0)) {
                ClockThread.sleep(1000);
                int minutos = time / 60;
                int segundos = time % 60;
                if (time <= 15) {
                    jLabelTempo.setForeground(Color.red);
                }
                jLabelTempo.setText(String.format("%02d:%02d", minutos, segundos));
                time--;
                if (time < 0) {
                    runFlag = false;
                }
            }
            // Termina Questoes
            jButtonQuestoesSeguinte.setText("Terminar");
            questaoAtual = 20;
            if (time < 0) verificaRespostas();
            jButtonQuestoesSeguinte.setEnabled(false);
        } catch (InterruptedException ex) {
            Logger.getLogger(ClockThread.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void jButtonQuestoesSeguinteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuestoesSeguinteActionPerformed
        respostas[questaoAtual - 1] = escolha;
        if (jButtonQuestoesSeguinte.getText().equals("Terminar")){
            runFlag = false;
            verificaRespostas();
            jButtonQuestoesSeguinte.setEnabled(false);
        }
        if (questaoAtual < 20) {
            questaoAtual++;
            criarQuestoesVEspacial(questaoAtual);
            criarQuestoesVEspacial(questaoAtual); // ???????
            if (questaoAtual==20){
                jButtonQuestoesSeguinte.setText("Terminar");
            }
        }
    }//GEN-LAST:event_jButtonQuestoesSeguinteActionPerformed

    private void verificaRespostas(){
       
        DefaultTableModel modelo = (DefaultTableModel)jTableResultadosVE.getModel();
        modelo.setRowCount(0);
        jTableResultadosVE.setDefaultRenderer(Object.class, new CustomRenderer());
        
        TableColumnModel columnModel = jTableResultadosVE.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(30);
        columnModel.getColumn(1).setPreferredWidth(30);
        columnModel.getColumn(2).setPreferredWidth(30);
        columnModel.getColumn(3).setPreferredWidth(120);

        String respostasfinal = "";
        int nacertos = 0;
        
        for (int i = 0; i < 20; i++) {
            if (respostas[i]==solucao[i]){
                respostasfinal += "1";
                nacertos++;
            } else {
                respostasfinal += "0";
            }
            Object []dados = {(i+1), // Número Questão
                            solucao[i],
                            respostas[i],
                            ((respostasfinal.charAt(i)=='1')?"Resposta Correta":"Resposta Incorreta")
            };
            
            modelo.addRow(dados);
            
                       
        }
        
        jLabelOutResultadosVE.setText("Resultado: "+nacertos+"/20");
        jTabbedPaneVEspacial.add(jPanelResultados);
        jTabbedPaneVEspacial.setTitleAt(3, "Resultados");
        jTabbedPaneVEspacial.setSelectedIndex(3);
        jTabbedPaneVEspacial.repaint();
        
        DadosVEspacial dados = new DadosVEspacial(nacertos, respostasfinal);

    }
    
    
    
    private void carregaImagensVEspacial() {
        for (int i = 1; i <= 20; i++) {
            tImagensVEspacial.add(new javax.swing.ImageIcon(getClass().getResource("/imagensVEspacial/p" + i + ".png")));
        }
    }

    private void criarQuestoesVEspacial(int index) {
        escolha = 'X';
        jPanelQ1.setLayout(null);
        // Resposta A
        jLabelP1A.setToolTipText("A");
        jLabelP1A.setName(""); 
        jLabelP1A.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jLabelP1A.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMouseClicked(evt, 'A');
            }
        });
        jPanelQ1.add(jLabelP1A);
        jLabelP1A.setBounds(335, 120, 50, 90);
        // Resposta B
        jLabelP1B.setToolTipText("B");
        jLabelP1B.setName("");
        jLabelP1B.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jLabelP1B.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMouseClicked(evt, 'B');
            }
        });
        jPanelQ1.add(jLabelP1B);
        jLabelP1B.setBounds(385, 120, 50, 90);
        // Resposta C    
        jLabelP1C.setToolTipText("C");
        jLabelP1C.setName("");
        jLabelP1C.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jLabelP1C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMouseClicked(evt, 'C');
            }
        });
        jPanelQ1.add(jLabelP1C);
        jLabelP1C.setBounds(435, 120, 50, 90);
        // Resposta D    
        jLabelP1D.setToolTipText("D");
        jLabelP1D.setName("");
        jLabelP1D.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jLabelP1D.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMouseClicked(evt, 'D');
            }
        });
        jPanelQ1.add(jLabelP1D);
        jLabelP1D.setBounds(485, 120, 50, 90);
        // Resposta E
        jLabelP1E.setToolTipText("E");
        jLabelP1E.setName("");
        jLabelP1E.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jLabelP1E.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMouseClicked(evt, 'E');
            }
        });
        jPanelQ1.add(jLabelP1E);
        jLabelP1E.setBounds(535, 120, 50, 90);

        jLabelP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensVEspacial/p" + index + ".png"))); // NOI18N
        jPanelQ1.add(jLabelP1);
        jLabelP1.setBounds(66, 113, 555, 105);

        jPanelQ1.add(jButtonQuestoesSeguinte);
        jButtonQuestoesSeguinte.setBounds(523, 320, 100, 23);

        jTabbedPaneVEspacial.setTitleAt(2, String.format("Q%02d", index));
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JButton jButtonInstrucoesAnterior;
    private javax.swing.JButton jButtonInstrucoesSeguinte;
    private javax.swing.JButton jButtonQuestoesSeguinte;
    private javax.swing.JDialog jDialogTesteVEspacial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFig0;
    private javax.swing.JLabel jLabelFig01;
    private javax.swing.JLabel jLabelOutResultadosVE;
    private javax.swing.JLabel jLabelP1;
    private javax.swing.JLabel jLabelP1A;
    private javax.swing.JLabel jLabelP1B;
    private javax.swing.JLabel jLabelP1C;
    private javax.swing.JLabel jLabelP1D;
    private javax.swing.JLabel jLabelP1E;
    private javax.swing.JLabel jLabelTempo;
    private javax.swing.JPanel jPanelInstrucoes;
    private javax.swing.JPanel jPanelQ1;
    private javax.swing.JPanel jPanelR0;
    private javax.swing.JPanel jPanelResultados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPaneVEspacial;
    private javax.swing.JTable jTableResultadosVE;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTextPane jTextPane5;
    // End of variables declaration//GEN-END:variables
    ArrayList tImagensVEspacial = new ArrayList();
    char [] respostas = {'X','X','X','X','X','X','X','X','X','X','X','X','X','X','X','X','X','X','X','X'};
    char [] solucao = {'A','D','B','D','B','E','A','C','E','E','C','B','A','E','E','A','E','D','D','C'};
    char escolha = 'X';
    int questaoAtual = 1;

    JLabel[] labelEscolha = new JLabel[5];
    
    boolean runFlag = true;
    Thread clockThread = null;
   

}
