/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import com.mysql.jdbc.Connection;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.DadosQuestionario;
import modelo.Questionario;
import modelo.Resposta;
import service.ConnectBD;

/**
 *
 * @author Utilizador
 */
public class BasicActivities extends javax.swing.JPanel {

    /**
     * Creates new form BasicActivities
     */
    public BasicActivities(ConnectBD c) {
        initComponents();
        liga = new ConnectBD();
        DadosQuestionario dQuestions = new DadosQuestionario(c);
        carregaQuestionario(); 
        
        jDialogBasicActSettings.setLocationRelativeTo(this);
        jDialogBasicActSettings.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogBasicActSettings = new javax.swing.JDialog();
        jPanelTopic = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxTopic = new javax.swing.JComboBox<>();
        jButtonAddNewTopic = new javax.swing.JButton();
        jTextFieldNewTopic = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableQuestion = new javax.swing.JTable();
        jPanelAddQuestion = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldQuestion = new javax.swing.JTextField();
        jButtonAddQuestion = new javax.swing.JButton();
        jButtonAddNewAnswers = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAnswers = new javax.swing.JTable();
        jButtonSaveQandA = new javax.swing.JButton();
        jDialogAddAnswer = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldTextAddAnswer = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldResultAddAnswer = new javax.swing.JTextField();
        jButtonAddTableAnswer = new javax.swing.JButton();

        jDialogBasicActSettings.setTitle("Questions and Answers");
        jDialogBasicActSettings.setMinimumSize(new java.awt.Dimension(700, 650));

        jPanelTopic.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Topic:");

        jComboBoxTopic.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxTopic.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBoxTopicPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jButtonAddNewTopic.setText("Add New Topic");
        jButtonAddNewTopic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddNewTopicActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTopicLayout = new javax.swing.GroupLayout(jPanelTopic);
        jPanelTopic.setLayout(jPanelTopicLayout);
        jPanelTopicLayout.setHorizontalGroup(
            jPanelTopicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopicLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanelTopicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelTopicLayout.createSequentialGroup()
                        .addComponent(jTextFieldNewTopic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAddNewTopic))
                    .addComponent(jComboBoxTopic, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );
        jPanelTopicLayout.setVerticalGroup(
            jPanelTopicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopicLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTopicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxTopic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelTopicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddNewTopic)
                    .addComponent(jTextFieldNewTopic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableQuestion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Question"
            }
        ));
        jTableQuestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableQuestionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableQuestion);

        jPanelAddQuestion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Question:");

        jButtonAddQuestion.setText("Add Question");
        jButtonAddQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddQuestionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAddQuestionLayout = new javax.swing.GroupLayout(jPanelAddQuestion);
        jPanelAddQuestion.setLayout(jPanelAddQuestionLayout);
        jPanelAddQuestionLayout.setHorizontalGroup(
            jPanelAddQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddQuestionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAddQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanelAddQuestionLayout.setVerticalGroup(
            jPanelAddQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddQuestionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAddQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddQuestion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonAddNewAnswers.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonAddNewAnswers.setText("Add Answers");
        jButtonAddNewAnswers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddNewAnswersActionPerformed(evt);
            }
        });

        jTableAnswers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Text Answer", "Result"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableAnswers);

        jButtonSaveQandA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonSaveQandA.setText("Save");
        jButtonSaveQandA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveQandAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogBasicActSettingsLayout = new javax.swing.GroupLayout(jDialogBasicActSettings.getContentPane());
        jDialogBasicActSettings.getContentPane().setLayout(jDialogBasicActSettingsLayout);
        jDialogBasicActSettingsLayout.setHorizontalGroup(
            jDialogBasicActSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogBasicActSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogBasicActSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jDialogBasicActSettingsLayout.createSequentialGroup()
                        .addGroup(jDialogBasicActSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelTopic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelAddQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAddNewAnswers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogBasicActSettingsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSaveQandA, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jDialogBasicActSettingsLayout.setVerticalGroup(
            jDialogBasicActSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogBasicActSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTopic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAddQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAddNewAnswers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSaveQandA)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDialogAddAnswer.setTitle("Add Answer");
        jDialogAddAnswer.setMinimumSize(new java.awt.Dimension(400, 150));

        jLabel3.setText("Text Answer:");

        jLabel4.setText("Result:");

        jTextFieldResultAddAnswer.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldResultAddAnswer.setText("0");

        jButtonAddTableAnswer.setText("Add");
        jButtonAddTableAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddTableAnswerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogAddAnswerLayout = new javax.swing.GroupLayout(jDialogAddAnswer.getContentPane());
        jDialogAddAnswer.getContentPane().setLayout(jDialogAddAnswerLayout);
        jDialogAddAnswerLayout.setHorizontalGroup(
            jDialogAddAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAddAnswerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogAddAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jDialogAddAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldTextAddAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDialogAddAnswerLayout.createSequentialGroup()
                        .addComponent(jTextFieldResultAddAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAddTableAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jDialogAddAnswerLayout.setVerticalGroup(
            jDialogAddAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAddAnswerLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jDialogAddAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldTextAddAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogAddAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldResultAddAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddTableAnswer))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddQuestionActionPerformed
        String newQuestion = jTextFieldQuestion.getText();
        if (!(temaActivo.equals(""))) {
            if (!(newQuestion.equals(""))) {
                DefaultTableModel modeloQ = (DefaultTableModel) jTableQuestion.getModel();
                Object[] dados = {newQuestion};
                modeloQ.addRow(dados);
                DadosQuestionario.gravaNovaPerguntaTema(liga,newQuestion, temaActivo);
                idPerguntaActivo = DadosQuestionario.getLastIDPergunta(liga);

                tQ = DadosQuestionario.gettQuestionario(liga);
                jTableQuestion.setRowSelectionInterval(modeloQ.getRowCount()-1, modeloQ.getRowCount()-1);
            } else {
                JOptionPane.showMessageDialog(jPanelAddQuestion, "Question is EMPTY!");
            }
        } else {
            JOptionPane.showMessageDialog(jPanelAddQuestion, "Topic is EMPTY or Not Select!");
        }
//        idPerguntaActivo = DadosQuestionario.getLastIDPergunta();
        
    }//GEN-LAST:event_jButtonAddQuestionActionPerformed

    private void jComboBoxTopicPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBoxTopicPopupMenuWillBecomeInvisible
//        tQ = DadosQuestionario.gettQuestionario();
        temaActivo = jComboBoxTopic.getSelectedItem().toString();
        idPerguntaActivo = -1;
        DefaultTableModel modeloQ = (DefaultTableModel) jTableQuestion.getModel();
        modeloQ.setRowCount(0);
        DefaultTableModel modeloR = (DefaultTableModel) jTableAnswers.getModel();
        modeloR.setRowCount(0);
        for (Questionario q : tQ) {
            if (q.getTema().equals(temaActivo)) {
                Object[] dados = {q.getPergunta()};
                modeloQ.addRow(dados);
            }
        }
    }//GEN-LAST:event_jComboBoxTopicPopupMenuWillBecomeInvisible

    private void jButtonAddNewTopicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddNewTopicActionPerformed
        idPerguntaActivo = -1;
        newTema = jTextFieldNewTopic.getText();
        if (!(newTema.equals(""))) {
            temaActivo = newTema;
            DadosQuestionario.gravaNovoTema(liga,newTema);
            DadosQuestionario.lerTemasToComboBox(liga,jComboBoxTopic);
            ComboBoxModel modelo = jComboBoxTopic.getModel();
            modelo.setSelectedItem(temaActivo);
        } else {
            JOptionPane.showMessageDialog(jPanelTopic, "New Topic is EMPTY!");
        }
        
    }//GEN-LAST:event_jButtonAddNewTopicActionPerformed

    private void jTableQuestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableQuestionMouseClicked
        int linha = jTableQuestion.getSelectedRow();
        idPerguntaActivo = -1;
        if (linha >= 0) {
            String perg = jTableQuestion.getValueAt(linha, 0).toString();
            DefaultTableModel modelo = (DefaultTableModel) jTableAnswers.getModel();
            modelo.setRowCount(0);
            for (Questionario q : tQ) {
                if (q.getTema().equals(temaActivo) && (perg.equals(q.getPergunta()))) {
                    idPerguntaActivo = q.getIdPergunta();
                    ArrayList<Resposta> tr = q.getRespostas();
                    for (int i = 0; i < tr.size(); i++) {
                        Object[] dados = {(i+1),tr.get(i).getDescricao(),tr.get(i).getValor()};
                        modelo.addRow(dados);
                    }
                }
            }
        } 
        
    }//GEN-LAST:event_jTableQuestionMouseClicked

    private void jButtonAddNewAnswersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddNewAnswersActionPerformed
        int linha = jTableQuestion.getSelectedRow();
        if (linha >= 0) {
            jDialogAddAnswer.setLocationRelativeTo(jDialogBasicActSettings);
            jDialogAddAnswer.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(jDialogBasicActSettings, "Select Question ...");
        }
    }//GEN-LAST:event_jButtonAddNewAnswersActionPerformed

    private void jButtonAddTableAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddTableAnswerActionPerformed
        jDialogAddAnswer.setVisible(false);
        // Adicionar na tabela de respostas
        String text = jTextFieldTextAddAnswer.getText();
        if (!(text.equals(""))) {
            int result = Integer.parseInt(jTextFieldResultAddAnswer.getText());
            DefaultTableModel modeloR = (DefaultTableModel) jTableAnswers.getModel();
            int nLinhas = modeloR.getRowCount();
            Object[] dados = {nLinhas, text, result};
            modeloR.addRow(dados);            
        } else {
            JOptionPane.showMessageDialog(jDialogBasicActSettings, "New Answer is EMPTY!");
        }
        jTextFieldTextAddAnswer.setText("");
    }//GEN-LAST:event_jButtonAddTableAnswerActionPerformed

    private void jButtonSaveQandAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveQandAActionPerformed
        DefaultTableModel modeloR = (DefaultTableModel) jTableAnswers.getModel();
//        System.out.println("ID Pergunta: "+idPerguntaActivo);
        if (idPerguntaActivo>0){
            DadosQuestionario.removeResposta(liga,idPerguntaActivo);
            for (int i = 0; i < modeloR.getRowCount(); i++) {
                String resposta = modeloR.getValueAt(i, 1).toString();
                int valor = Integer.parseInt(modeloR.getValueAt(i, 2).toString());
                DadosQuestionario.gravaNovaResposta(liga,idPerguntaActivo, resposta, valor);
            }
            tQ.removeAll(tQ);
            tQ = DadosQuestionario.gettQuestionario(liga);
        } else {
            JOptionPane.showMessageDialog(jDialogBasicActSettings, "ID Pergunta incorrect!");
        }
    }//GEN-LAST:event_jButtonSaveQandAActionPerformed

  
    
    private void carregaQuestionario(){
//        DadosQuestionario dQuestions = new DadosQuestionario();
        tQ.removeAll(tQ);
        tQ = DadosQuestionario.gettQuestionario(liga);
        DadosQuestionario.lerTemasToComboBox(liga,jComboBoxTopic);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddNewAnswers;
    private javax.swing.JButton jButtonAddNewTopic;
    private javax.swing.JButton jButtonAddQuestion;
    private javax.swing.JButton jButtonAddTableAnswer;
    private javax.swing.JButton jButtonSaveQandA;
    private javax.swing.JComboBox<String> jComboBoxTopic;
    private javax.swing.JDialog jDialogAddAnswer;
    private javax.swing.JDialog jDialogBasicActSettings;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanelAddQuestion;
    private javax.swing.JPanel jPanelTopic;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableAnswers;
    private javax.swing.JTable jTableQuestion;
    private javax.swing.JTextField jTextFieldNewTopic;
    private javax.swing.JTextField jTextFieldQuestion;
    private javax.swing.JTextField jTextFieldResultAddAnswer;
    private javax.swing.JTextField jTextFieldTextAddAnswer;
    // End of variables declaration//GEN-END:variables

    ConnectBD liga = null;
    
    ArrayList<Questionario> tQ = new ArrayList();
    String temaActivo = ""; // Tema activo
    String newTema = "";
    int idPerguntaActivo = -1;
}
