/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import modelo.DadosCAP;

/**
 *
 * @author Utilizador
 */
public class CaraterizacaoAluno extends javax.swing.JPanel {

    /**
     * Creates new form CaraterizacaoAluno
     */
    public CaraterizacaoAluno() {
        initComponents();
        jDialogCaraterizacaoAluno.setLocationRelativeTo(this);
        jDialogCaraterizacaoAluno.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogCaraterizacaoAluno = new javax.swing.JDialog();
        jTabbedPaneQuestionario = new javax.swing.JTabbedPane();
        jPanelQ1 = new javax.swing.JPanel();
        jLabelQ1 = new javax.swing.JLabel();
        jRadioButtonCAP1_1 = new javax.swing.JRadioButton();
        jRadioButtonCAP1_2 = new javax.swing.JRadioButton();
        jRadioButtonCAP1_3 = new javax.swing.JRadioButton();
        jRadioButtonCAP1_4 = new javax.swing.JRadioButton();
        jRadioButtonCAP1_5 = new javax.swing.JRadioButton();
        jButtonQ1Next = new javax.swing.JButton();
        jPanelQ2 = new javax.swing.JPanel();
        jLabelQ2 = new javax.swing.JLabel();
        jRadioButtonCAP2_1 = new javax.swing.JRadioButton();
        jRadioButtonCAP2_2 = new javax.swing.JRadioButton();
        jRadioButtonCAP2_3 = new javax.swing.JRadioButton();
        jRadioButtonCAP2_4 = new javax.swing.JRadioButton();
        jRadioButtonCAP2_5 = new javax.swing.JRadioButton();
        jButtonQ2Next = new javax.swing.JButton();
        jLabelQualOutroSuperior = new javax.swing.JLabel();
        jTextFieldOutroCAP2Curso = new javax.swing.JTextField();
        jPanelQ3 = new javax.swing.JPanel();
        jLabelQ3 = new javax.swing.JLabel();
        jRadioButtonCAP3_1 = new javax.swing.JRadioButton();
        jRadioButtonCAP3_2 = new javax.swing.JRadioButton();
        jButtonQ3Next = new javax.swing.JButton();
        jPanelQ4 = new javax.swing.JPanel();
        jLabelQ4 = new javax.swing.JLabel();
        jRadioButtonCAP4_1 = new javax.swing.JRadioButton();
        jRadioButtonCAP4_2 = new javax.swing.JRadioButton();
        jButtonQ4Next = new javax.swing.JButton();
        jPanelQ5 = new javax.swing.JPanel();
        jLabelQ5 = new javax.swing.JLabel();
        jRadioButtonCAP5_1 = new javax.swing.JRadioButton();
        jRadioButtonCAP5_2 = new javax.swing.JRadioButton();
        jButtonQ5Next = new javax.swing.JButton();
        jRadioButtonCAP5_3 = new javax.swing.JRadioButton();
        jRadioButtonCAP5_4 = new javax.swing.JRadioButton();
        jRadioButtonCAP5_5 = new javax.swing.JRadioButton();
        jRadioButtonCAP5_6 = new javax.swing.JRadioButton();
        jPanelQ6 = new javax.swing.JPanel();
        jLabelQ6 = new javax.swing.JLabel();
        jRadioButtonCAP6_1 = new javax.swing.JRadioButton();
        jRadioButtonCAP6_2 = new javax.swing.JRadioButton();
        jButtonQ6Next = new javax.swing.JButton();
        jRadioButtonCAP6_3 = new javax.swing.JRadioButton();
        jRadioButtonCAP6_4 = new javax.swing.JRadioButton();
        jRadioButtonCAP6_5 = new javax.swing.JRadioButton();
        jRadioButtonCAP6_6 = new javax.swing.JRadioButton();
        jPanelQ7 = new javax.swing.JPanel();
        jLabelQ7 = new javax.swing.JLabel();
        jRadioButtonCAP7_1 = new javax.swing.JRadioButton();
        jRadioButtonCAP7_2 = new javax.swing.JRadioButton();
        jButtonQ7Next = new javax.swing.JButton();
        jRadioButtonCAP7_3 = new javax.swing.JRadioButton();
        jRadioButtonCAP7_4 = new javax.swing.JRadioButton();
        jRadioButtonCAP7_5 = new javax.swing.JRadioButton();
        jRadioButtonCAP7_6 = new javax.swing.JRadioButton();
        jRadioButtonCAP7_7 = new javax.swing.JRadioButton();
        jRadioButtonCAP7_8 = new javax.swing.JRadioButton();
        jLabelQ7Qual = new javax.swing.JLabel();
        jTextFieldCAP7_8 = new javax.swing.JTextField();
        jPanelQ8 = new javax.swing.JPanel();
        jLabelQ8 = new javax.swing.JLabel();
        jButtonTerminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSpinnerCAP8 = new javax.swing.JSpinner();
        jLabelQ9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldMediaCandidatura = new javax.swing.JTextField();
        buttonGroupCAP1 = new javax.swing.ButtonGroup();
        buttonGroupCAP2 = new javax.swing.ButtonGroup();
        buttonGroupCAP3 = new javax.swing.ButtonGroup();
        buttonGroupCAP4 = new javax.swing.ButtonGroup();
        buttonGroupCAP5 = new javax.swing.ButtonGroup();
        buttonGroupCAP6 = new javax.swing.ButtonGroup();

        jDialogCaraterizacaoAluno.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        jDialogCaraterizacaoAluno.setTitle("Caraterização do Aluno em Programação");
        jDialogCaraterizacaoAluno.setMinimumSize(new java.awt.Dimension(590, 350));
        jDialogCaraterizacaoAluno.setModal(true);

        jTabbedPaneQuestionario.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPaneQuestionario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabelQ1.setBackground(new java.awt.Color(153, 204, 255));
        jLabelQ1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelQ1.setText("Q1: Número de matrículas na unidade curricular de Introdução à Programação?");
        jLabelQ1.setOpaque(true);

        buttonGroupCAP1.add(jRadioButtonCAP1_1);
        jRadioButtonCAP1_1.setMnemonic('\u0001');
        jRadioButtonCAP1_1.setSelected(true);
        jRadioButtonCAP1_1.setText("1 - Primeira Vez");

        buttonGroupCAP1.add(jRadioButtonCAP1_2);
        jRadioButtonCAP1_2.setMnemonic('\u0002');
        jRadioButtonCAP1_2.setText("2");

        buttonGroupCAP1.add(jRadioButtonCAP1_3);
        jRadioButtonCAP1_3.setMnemonic('\u0003');
        jRadioButtonCAP1_3.setText("3");

        buttonGroupCAP1.add(jRadioButtonCAP1_4);
        jRadioButtonCAP1_4.setMnemonic('\u0004');
        jRadioButtonCAP1_4.setText("4");

        buttonGroupCAP1.add(jRadioButtonCAP1_5);
        jRadioButtonCAP1_5.setMnemonic('\u0005');
        jRadioButtonCAP1_5.setText("5 Ou mais vezes");

        jButtonQ1Next.setText("Seguinte");
        jButtonQ1Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQ1NextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelQ1Layout = new javax.swing.GroupLayout(jPanelQ1);
        jPanelQ1.setLayout(jPanelQ1Layout);
        jPanelQ1Layout.setHorizontalGroup(
            jPanelQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQ1Layout.createSequentialGroup()
                .addGroup(jPanelQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonQ1Next, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelQ1Layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(jLabelQ1))
                        .addGroup(jPanelQ1Layout.createSequentialGroup()
                            .addGap(62, 62, 62)
                            .addGroup(jPanelQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRadioButtonCAP1_2)
                                .addComponent(jRadioButtonCAP1_1)
                                .addComponent(jRadioButtonCAP1_3)
                                .addComponent(jRadioButtonCAP1_4)
                                .addComponent(jRadioButtonCAP1_5)))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanelQ1Layout.setVerticalGroup(
            jPanelQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQ1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelQ1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonCAP1_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonCAP1_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonCAP1_3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonCAP1_4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonCAP1_5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jButtonQ1Next)
                .addGap(19, 19, 19))
        );

        jTabbedPaneQuestionario.addTab("Q1", jPanelQ1);

        jLabelQ2.setBackground(new java.awt.Color(153, 204, 255));
        jLabelQ2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelQ2.setText("Q2: Qual o Curso Anterior?");
        jLabelQ2.setOpaque(true);

        buttonGroupCAP2.add(jRadioButtonCAP2_1);
        jRadioButtonCAP2_1.setMnemonic('\u0001');
        jRadioButtonCAP2_1.setSelected(true);
        jRadioButtonCAP2_1.setText("Profissional/TeSP Área Programação");

        buttonGroupCAP2.add(jRadioButtonCAP2_2);
        jRadioButtonCAP2_2.setMnemonic('\u0002');
        jRadioButtonCAP2_2.setText("Ciências, com opção Programação");

        buttonGroupCAP2.add(jRadioButtonCAP2_3);
        jRadioButtonCAP2_3.setMnemonic('\u0003');
        jRadioButtonCAP2_3.setText("Ciências");

        buttonGroupCAP2.add(jRadioButtonCAP2_4);
        jRadioButtonCAP2_4.setMnemonic('\u0004');
        jRadioButtonCAP2_4.setText("Outro");

        buttonGroupCAP2.add(jRadioButtonCAP2_5);
        jRadioButtonCAP2_5.setMnemonic('\u0005');
        jRadioButtonCAP2_5.setText("Outro Curso Superior");

        jButtonQ2Next.setText("Seguinte");
        jButtonQ2Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQ2NextActionPerformed(evt);
            }
        });

        jLabelQualOutroSuperior.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelQualOutroSuperior.setText("Qual?");

        jTextFieldOutroCAP2Curso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanelQ2Layout = new javax.swing.GroupLayout(jPanelQ2);
        jPanelQ2.setLayout(jPanelQ2Layout);
        jPanelQ2Layout.setHorizontalGroup(
            jPanelQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelQ2Layout.createSequentialGroup()
                .addGroup(jPanelQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelQ2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonQ2Next, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelQ2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabelQualOutroSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldOutroCAP2Curso, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                        .addGap(13, 13, 13)))
                .addGap(29, 29, 29))
            .addGroup(jPanelQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelQ2Layout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addGroup(jPanelQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelQ2Layout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addGroup(jPanelQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRadioButtonCAP2_2)
                                .addComponent(jRadioButtonCAP2_1)
                                .addComponent(jRadioButtonCAP2_3)
                                .addComponent(jRadioButtonCAP2_4)
                                .addComponent(jRadioButtonCAP2_5)))
                        .addComponent(jLabelQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelQ2Layout.setVerticalGroup(
            jPanelQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelQ2Layout.createSequentialGroup()
                .addContainerGap(208, Short.MAX_VALUE)
                .addGroup(jPanelQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelQualOutroSuperior)
                    .addComponent(jTextFieldOutroCAP2Curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButtonQ2Next)
                .addContainerGap())
            .addGroup(jPanelQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelQ2Layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(jLabelQ2)
                    .addGap(18, 18, 18)
                    .addComponent(jRadioButtonCAP2_1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jRadioButtonCAP2_2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jRadioButtonCAP2_3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jRadioButtonCAP2_4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jRadioButtonCAP2_5)
                    .addContainerGap(100, Short.MAX_VALUE)))
        );

        jTabbedPaneQuestionario.addTab("Q2", jPanelQ2);

        jLabelQ3.setBackground(new java.awt.Color(153, 204, 255));
        jLabelQ3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelQ3.setText("Q3: Tem computador pessoal?");
        jLabelQ3.setOpaque(true);

        buttonGroupCAP3.add(jRadioButtonCAP3_1);
        jRadioButtonCAP3_1.setMnemonic('\u0001');
        jRadioButtonCAP3_1.setSelected(true);
        jRadioButtonCAP3_1.setText("Sim");

        buttonGroupCAP3.add(jRadioButtonCAP3_2);
        jRadioButtonCAP3_2.setText("Não");

        jButtonQ3Next.setText("Seguinte");
        jButtonQ3Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQ3NextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelQ3Layout = new javax.swing.GroupLayout(jPanelQ3);
        jPanelQ3.setLayout(jPanelQ3Layout);
        jPanelQ3Layout.setHorizontalGroup(
            jPanelQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelQ3Layout.createSequentialGroup()
                .addContainerGap(425, Short.MAX_VALUE)
                .addComponent(jButtonQ3Next, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(jPanelQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelQ3Layout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addGroup(jPanelQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelQ3Layout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addGroup(jPanelQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRadioButtonCAP3_2)
                                .addComponent(jRadioButtonCAP3_1)))
                        .addComponent(jLabelQ3, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelQ3Layout.setVerticalGroup(
            jPanelQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelQ3Layout.createSequentialGroup()
                .addContainerGap(260, Short.MAX_VALUE)
                .addComponent(jButtonQ3Next)
                .addContainerGap())
            .addGroup(jPanelQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelQ3Layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(jLabelQ3)
                    .addGap(18, 18, 18)
                    .addComponent(jRadioButtonCAP3_1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jRadioButtonCAP3_2)
                    .addContainerGap(178, Short.MAX_VALUE)))
        );

        jTabbedPaneQuestionario.addTab("Q3", jPanelQ3);

        jLabelQ4.setBackground(new java.awt.Color(153, 204, 255));
        jLabelQ4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelQ4.setText("Q4: Tem ligação à Internet fora da Escola?");
        jLabelQ4.setOpaque(true);

        buttonGroupCAP4.add(jRadioButtonCAP4_1);
        jRadioButtonCAP4_1.setMnemonic('\u0001');
        jRadioButtonCAP4_1.setSelected(true);
        jRadioButtonCAP4_1.setText("Sim");

        buttonGroupCAP4.add(jRadioButtonCAP4_2);
        jRadioButtonCAP4_2.setText("Não");

        jButtonQ4Next.setText("Seguinte");
        jButtonQ4Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQ4NextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelQ4Layout = new javax.swing.GroupLayout(jPanelQ4);
        jPanelQ4.setLayout(jPanelQ4Layout);
        jPanelQ4Layout.setHorizontalGroup(
            jPanelQ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelQ4Layout.createSequentialGroup()
                .addContainerGap(425, Short.MAX_VALUE)
                .addComponent(jButtonQ4Next, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(jPanelQ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelQ4Layout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addGroup(jPanelQ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelQ4Layout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addGroup(jPanelQ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRadioButtonCAP4_2)
                                .addComponent(jRadioButtonCAP4_1)))
                        .addComponent(jLabelQ4, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelQ4Layout.setVerticalGroup(
            jPanelQ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelQ4Layout.createSequentialGroup()
                .addContainerGap(260, Short.MAX_VALUE)
                .addComponent(jButtonQ4Next)
                .addContainerGap())
            .addGroup(jPanelQ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelQ4Layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(jLabelQ4)
                    .addGap(18, 18, 18)
                    .addComponent(jRadioButtonCAP4_1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jRadioButtonCAP4_2)
                    .addContainerGap(178, Short.MAX_VALUE)))
        );

        jTabbedPaneQuestionario.addTab("Q4", jPanelQ4);

        jLabelQ5.setBackground(new java.awt.Color(153, 204, 255));
        jLabelQ5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelQ5.setText("Q5: Como avalia os seus conhecimentos gerais em informática?");
        jLabelQ5.setOpaque(true);

        buttonGroupCAP5.add(jRadioButtonCAP5_1);
        jRadioButtonCAP5_1.setSelected(true);
        jRadioButtonCAP5_1.setText("0 - Nulos");

        buttonGroupCAP5.add(jRadioButtonCAP5_2);
        jRadioButtonCAP5_2.setMnemonic('\u0001');
        jRadioButtonCAP5_2.setText("1 - Muito Fracos");

        jButtonQ5Next.setText("Seguinte");
        jButtonQ5Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQ5NextActionPerformed(evt);
            }
        });

        buttonGroupCAP5.add(jRadioButtonCAP5_3);
        jRadioButtonCAP5_3.setMnemonic('\u0002');
        jRadioButtonCAP5_3.setText("2 - Fracos");

        buttonGroupCAP5.add(jRadioButtonCAP5_4);
        jRadioButtonCAP5_4.setMnemonic('\u0003');
        jRadioButtonCAP5_4.setText("3 - Razoáveis");

        buttonGroupCAP5.add(jRadioButtonCAP5_5);
        jRadioButtonCAP5_5.setMnemonic('\u0004');
        jRadioButtonCAP5_5.setText("4 - Bons");

        buttonGroupCAP5.add(jRadioButtonCAP5_6);
        jRadioButtonCAP5_6.setMnemonic('\u0005');
        jRadioButtonCAP5_6.setText("5 - Muito Bons");

        javax.swing.GroupLayout jPanelQ5Layout = new javax.swing.GroupLayout(jPanelQ5);
        jPanelQ5.setLayout(jPanelQ5Layout);
        jPanelQ5Layout.setHorizontalGroup(
            jPanelQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelQ5Layout.createSequentialGroup()
                .addContainerGap(425, Short.MAX_VALUE)
                .addComponent(jButtonQ5Next, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(jPanelQ5Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanelQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonCAP5_1)
                    .addComponent(jRadioButtonCAP5_2)
                    .addComponent(jRadioButtonCAP5_6)
                    .addComponent(jRadioButtonCAP5_5)
                    .addComponent(jRadioButtonCAP5_4)
                    .addComponent(jRadioButtonCAP5_3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelQ5Layout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(jLabelQ5, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelQ5Layout.setVerticalGroup(
            jPanelQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelQ5Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(jRadioButtonCAP5_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonCAP5_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonCAP5_3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonCAP5_4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonCAP5_5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonCAP5_6)
                .addGap(34, 34, 34)
                .addComponent(jButtonQ5Next)
                .addContainerGap())
            .addGroup(jPanelQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelQ5Layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(jLabelQ5)
                    .addContainerGap(245, Short.MAX_VALUE)))
        );

        jTabbedPaneQuestionario.addTab("Q5", jPanelQ5);

        jLabelQ6.setBackground(new java.awt.Color(153, 204, 255));
        jLabelQ6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelQ6.setText("Q6: Como avalia os seus conhecimentos em programação?");
        jLabelQ6.setOpaque(true);

        buttonGroupCAP6.add(jRadioButtonCAP6_1);
        jRadioButtonCAP6_1.setSelected(true);
        jRadioButtonCAP6_1.setText("0 - Nulos");

        buttonGroupCAP6.add(jRadioButtonCAP6_2);
        jRadioButtonCAP6_2.setMnemonic('\u0001');
        jRadioButtonCAP6_2.setText("1 - Muito Fracos");

        jButtonQ6Next.setText("Seguinte");
        jButtonQ6Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQ6NextActionPerformed(evt);
            }
        });

        buttonGroupCAP6.add(jRadioButtonCAP6_3);
        jRadioButtonCAP6_3.setMnemonic('\u0002');
        jRadioButtonCAP6_3.setText("2 - Fracos");

        buttonGroupCAP6.add(jRadioButtonCAP6_4);
        jRadioButtonCAP6_4.setMnemonic('\u0003');
        jRadioButtonCAP6_4.setText("3 - Razoáveis");

        buttonGroupCAP6.add(jRadioButtonCAP6_5);
        jRadioButtonCAP6_5.setMnemonic('\u0004');
        jRadioButtonCAP6_5.setText("4 - Bons");

        buttonGroupCAP6.add(jRadioButtonCAP6_6);
        jRadioButtonCAP6_6.setMnemonic('\u0005');
        jRadioButtonCAP6_6.setText("5 - Muito Bons");

        javax.swing.GroupLayout jPanelQ6Layout = new javax.swing.GroupLayout(jPanelQ6);
        jPanelQ6.setLayout(jPanelQ6Layout);
        jPanelQ6Layout.setHorizontalGroup(
            jPanelQ6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelQ6Layout.createSequentialGroup()
                .addContainerGap(425, Short.MAX_VALUE)
                .addComponent(jButtonQ6Next, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(jPanelQ6Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanelQ6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonCAP6_1)
                    .addComponent(jRadioButtonCAP6_2)
                    .addComponent(jRadioButtonCAP6_6)
                    .addComponent(jRadioButtonCAP6_5)
                    .addComponent(jRadioButtonCAP6_4)
                    .addComponent(jRadioButtonCAP6_3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelQ6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelQ6Layout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(jLabelQ6, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelQ6Layout.setVerticalGroup(
            jPanelQ6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelQ6Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(jRadioButtonCAP6_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonCAP6_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonCAP6_3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonCAP6_4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonCAP6_5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonCAP6_6)
                .addGap(34, 34, 34)
                .addComponent(jButtonQ6Next)
                .addContainerGap())
            .addGroup(jPanelQ6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelQ6Layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(jLabelQ6)
                    .addContainerGap(245, Short.MAX_VALUE)))
        );

        jTabbedPaneQuestionario.addTab("Q6", jPanelQ6);

        jLabelQ7.setBackground(new java.awt.Color(153, 204, 255));
        jLabelQ7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelQ7.setText("Q7: Quais as linguagens de programação que já utilizou?");
        jLabelQ7.setOpaque(true);

        jRadioButtonCAP7_1.setText("Pascal");

        jRadioButtonCAP7_2.setMnemonic('\u0001');
        jRadioButtonCAP7_2.setText("C");

        jButtonQ7Next.setText("Seguinte");
        jButtonQ7Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQ7NextActionPerformed(evt);
            }
        });

        jRadioButtonCAP7_3.setMnemonic('\u0002');
        jRadioButtonCAP7_3.setText("C++");

        jRadioButtonCAP7_4.setMnemonic('\u0003');
        jRadioButtonCAP7_4.setText("C#");

        jRadioButtonCAP7_5.setMnemonic('\u0004');
        jRadioButtonCAP7_5.setText("Java");

        jRadioButtonCAP7_6.setMnemonic('\u0005');
        jRadioButtonCAP7_6.setText("VisualBasic");

        jRadioButtonCAP7_7.setMnemonic('\u0006');
        jRadioButtonCAP7_7.setText("Phyton");

        jRadioButtonCAP7_8.setMnemonic('\u0007');
        jRadioButtonCAP7_8.setText("Outra");

        jLabelQ7Qual.setText("Qual?");

        javax.swing.GroupLayout jPanelQ7Layout = new javax.swing.GroupLayout(jPanelQ7);
        jPanelQ7.setLayout(jPanelQ7Layout);
        jPanelQ7Layout.setHorizontalGroup(
            jPanelQ7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQ7Layout.createSequentialGroup()
                .addGroup(jPanelQ7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelQ7Layout.createSequentialGroup()
                        .addGroup(jPanelQ7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelQ7Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addGroup(jPanelQ7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonCAP7_7)
                                    .addComponent(jRadioButtonCAP7_1)
                                    .addComponent(jRadioButtonCAP7_2)
                                    .addComponent(jRadioButtonCAP7_6)
                                    .addComponent(jRadioButtonCAP7_5)
                                    .addComponent(jRadioButtonCAP7_4)
                                    .addComponent(jRadioButtonCAP7_3)
                                    .addGroup(jPanelQ7Layout.createSequentialGroup()
                                        .addComponent(jRadioButtonCAP7_8)
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabelQ7Qual)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldCAP7_8, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanelQ7Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabelQ7, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelQ7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonQ7Next, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelQ7Layout.setVerticalGroup(
            jPanelQ7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelQ7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelQ7)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonCAP7_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonCAP7_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonCAP7_3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonCAP7_4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonCAP7_5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonCAP7_6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonCAP7_7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelQ7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelQ7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelQ7Qual)
                        .addComponent(jTextFieldCAP7_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jRadioButtonCAP7_8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonQ7Next)
                .addGap(13, 13, 13))
        );

        jTabbedPaneQuestionario.addTab("Q7", jPanelQ7);

        jLabelQ8.setBackground(new java.awt.Color(153, 204, 255));
        jLabelQ8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelQ8.setText("Q8: Qual a opção em que escolheu o curso Engª. Informática do IPG ?");
        jLabelQ8.setOpaque(true);

        jButtonTerminar.setText("Terminar");
        jButtonTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTerminarActionPerformed(evt);
            }
        });

        jLabel1.setText("Número da opção:");

        jSpinnerCAP8.setModel(new javax.swing.SpinnerNumberModel(1, 1, 6, 1));

        jLabelQ9.setBackground(new java.awt.Color(153, 204, 255));
        jLabelQ9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelQ9.setText("Q9: Qual a sua média de candidatura?");
        jLabelQ9.setOpaque(true);

        jLabel2.setText("Média de candidatura:");

        jTextFieldMediaCandidatura.setText("0.0");

        javax.swing.GroupLayout jPanelQ8Layout = new javax.swing.GroupLayout(jPanelQ8);
        jPanelQ8.setLayout(jPanelQ8Layout);
        jPanelQ8Layout.setHorizontalGroup(
            jPanelQ8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelQ8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(jPanelQ8Layout.createSequentialGroup()
                .addGroup(jPanelQ8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelQ8Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel1)
                        .addGap(76, 76, 76)
                        .addComponent(jSpinnerCAP8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelQ8Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel2)
                        .addGap(61, 61, 61)
                        .addComponent(jTextFieldMediaCandidatura, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelQ8Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabelQ9, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(jPanelQ8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelQ8Layout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(jLabelQ8, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelQ8Layout.setVerticalGroup(
            jPanelQ8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelQ8Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanelQ8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jSpinnerCAP8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabelQ9)
                .addGap(28, 28, 28)
                .addGroup(jPanelQ8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldMediaCandidatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jButtonTerminar)
                .addContainerGap())
            .addGroup(jPanelQ8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelQ8Layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(jLabelQ8)
                    .addContainerGap(245, Short.MAX_VALUE)))
        );

        jTabbedPaneQuestionario.addTab("Q8", jPanelQ8);

        javax.swing.GroupLayout jDialogCaraterizacaoAlunoLayout = new javax.swing.GroupLayout(jDialogCaraterizacaoAluno.getContentPane());
        jDialogCaraterizacaoAluno.getContentPane().setLayout(jDialogCaraterizacaoAlunoLayout);
        jDialogCaraterizacaoAlunoLayout.setHorizontalGroup(
            jDialogCaraterizacaoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogCaraterizacaoAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneQuestionario)
                .addContainerGap())
        );
        jDialogCaraterizacaoAlunoLayout.setVerticalGroup(
            jDialogCaraterizacaoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogCaraterizacaoAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneQuestionario)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void next() {
        int index = jTabbedPaneQuestionario.getSelectedIndex();
        jTabbedPaneQuestionario.setSelectedIndex(++index);
    }

    private void jButtonQ1NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQ1NextActionPerformed
        next();
    }//GEN-LAST:event_jButtonQ1NextActionPerformed

    private void jButtonQ2NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQ2NextActionPerformed
        String outroCurso = jTextFieldOutroCAP2Curso.getText();
        if (outroCurso.isEmpty()){
            JOptionPane.showMessageDialog(jPanelQ2, "Escreva a Designação do Curso");
            jTextFieldOutroCAP2Curso.requestFocusInWindow();
        } else {
            next();
        }
    }//GEN-LAST:event_jButtonQ2NextActionPerformed

    private void jButtonQ3NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQ3NextActionPerformed
        next();
    }//GEN-LAST:event_jButtonQ3NextActionPerformed

    private void jButtonQ4NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQ4NextActionPerformed
         next();
    }//GEN-LAST:event_jButtonQ4NextActionPerformed

    private void jButtonQ5NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQ5NextActionPerformed
         next();
    }//GEN-LAST:event_jButtonQ5NextActionPerformed

    private void jButtonQ6NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQ6NextActionPerformed
         next();
    }//GEN-LAST:event_jButtonQ6NextActionPerformed

    private void jButtonQ7NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQ7NextActionPerformed
        next();
    }//GEN-LAST:event_jButtonQ7NextActionPerformed

    private void jButtonTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTerminarActionPerformed
        // Gravar respostas Caraterização do Aluno
        int cap1 = (int)buttonGroupCAP1.getSelection().getMnemonic();
        int cap2 = (int)buttonGroupCAP2.getSelection().getMnemonic();
        String cursoCap2 = cap2+"#"+jTextFieldOutroCAP2Curso.getText();
        int cap3 =  (int)buttonGroupCAP3.getSelection().getMnemonic();
        int cap4 =  (int)buttonGroupCAP4.getSelection().getMnemonic();
        int cap5 =  (int)buttonGroupCAP5.getSelection().getMnemonic();
        int cap6 =  (int)buttonGroupCAP6.getSelection().getMnemonic();
        String cap7 = "";
        if (jRadioButtonCAP7_1.isSelected()) {
            cap7 += jRadioButtonCAP7_1.getText()+" ";
        }
        if (jRadioButtonCAP7_2.isSelected()) {
            cap7 += jRadioButtonCAP7_2.getText()+" ";
        }
        if (jRadioButtonCAP7_3.isSelected()) {
            cap7 += jRadioButtonCAP7_3.getText()+" ";
        }
        if (jRadioButtonCAP7_4.isSelected()) {
            cap7 += jRadioButtonCAP7_4.getText()+" ";
        }
        if (jRadioButtonCAP7_5.isSelected()) {
            cap7 += jRadioButtonCAP7_5.getText()+" ";
        }
        if (jRadioButtonCAP7_6.isSelected()) {
            cap7 += jRadioButtonCAP7_6.getText()+" ";
        }
        if (jRadioButtonCAP7_1.isSelected()) {
            cap7 += jRadioButtonCAP7_1.getText()+" ";
        }
        if (jRadioButtonCAP7_1.isSelected()) {
            cap7 += jTextFieldCAP7_8.getText();
        }
        int cap8 = Integer.parseInt(jSpinnerCAP8.getValue().toString());
        double cap9 = 0.0;
        try {
            cap9 = Double.parseDouble(jTextFieldMediaCandidatura.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(jDialogCaraterizacaoAluno, "Check Number Format (ex: 12.5");
        }
        DadosCAP dcap = new DadosCAP(cap1,cursoCap2,cap8,cap9,cap3,cap4,cap5,cap6,cap7);
        
        jDialogCaraterizacaoAluno.setVisible(false);
    }//GEN-LAST:event_jButtonTerminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupCAP1;
    private javax.swing.ButtonGroup buttonGroupCAP2;
    private javax.swing.ButtonGroup buttonGroupCAP3;
    private javax.swing.ButtonGroup buttonGroupCAP4;
    private javax.swing.ButtonGroup buttonGroupCAP5;
    private javax.swing.ButtonGroup buttonGroupCAP6;
    private javax.swing.JButton jButtonQ1Next;
    private javax.swing.JButton jButtonQ2Next;
    private javax.swing.JButton jButtonQ3Next;
    private javax.swing.JButton jButtonQ4Next;
    private javax.swing.JButton jButtonQ5Next;
    private javax.swing.JButton jButtonQ6Next;
    private javax.swing.JButton jButtonQ7Next;
    private javax.swing.JButton jButtonTerminar;
    private javax.swing.JDialog jDialogCaraterizacaoAluno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelQ1;
    private javax.swing.JLabel jLabelQ2;
    private javax.swing.JLabel jLabelQ3;
    private javax.swing.JLabel jLabelQ4;
    private javax.swing.JLabel jLabelQ5;
    private javax.swing.JLabel jLabelQ6;
    private javax.swing.JLabel jLabelQ7;
    private javax.swing.JLabel jLabelQ7Qual;
    private javax.swing.JLabel jLabelQ8;
    private javax.swing.JLabel jLabelQ9;
    private javax.swing.JLabel jLabelQualOutroSuperior;
    private javax.swing.JPanel jPanelQ1;
    private javax.swing.JPanel jPanelQ2;
    private javax.swing.JPanel jPanelQ3;
    private javax.swing.JPanel jPanelQ4;
    private javax.swing.JPanel jPanelQ5;
    private javax.swing.JPanel jPanelQ6;
    private javax.swing.JPanel jPanelQ7;
    private javax.swing.JPanel jPanelQ8;
    private javax.swing.JRadioButton jRadioButtonCAP1_1;
    private javax.swing.JRadioButton jRadioButtonCAP1_2;
    private javax.swing.JRadioButton jRadioButtonCAP1_3;
    private javax.swing.JRadioButton jRadioButtonCAP1_4;
    private javax.swing.JRadioButton jRadioButtonCAP1_5;
    private javax.swing.JRadioButton jRadioButtonCAP2_1;
    private javax.swing.JRadioButton jRadioButtonCAP2_2;
    private javax.swing.JRadioButton jRadioButtonCAP2_3;
    private javax.swing.JRadioButton jRadioButtonCAP2_4;
    private javax.swing.JRadioButton jRadioButtonCAP2_5;
    private javax.swing.JRadioButton jRadioButtonCAP3_1;
    private javax.swing.JRadioButton jRadioButtonCAP3_2;
    private javax.swing.JRadioButton jRadioButtonCAP4_1;
    private javax.swing.JRadioButton jRadioButtonCAP4_2;
    private javax.swing.JRadioButton jRadioButtonCAP5_1;
    private javax.swing.JRadioButton jRadioButtonCAP5_2;
    private javax.swing.JRadioButton jRadioButtonCAP5_3;
    private javax.swing.JRadioButton jRadioButtonCAP5_4;
    private javax.swing.JRadioButton jRadioButtonCAP5_5;
    private javax.swing.JRadioButton jRadioButtonCAP5_6;
    private javax.swing.JRadioButton jRadioButtonCAP6_1;
    private javax.swing.JRadioButton jRadioButtonCAP6_2;
    private javax.swing.JRadioButton jRadioButtonCAP6_3;
    private javax.swing.JRadioButton jRadioButtonCAP6_4;
    private javax.swing.JRadioButton jRadioButtonCAP6_5;
    private javax.swing.JRadioButton jRadioButtonCAP6_6;
    private javax.swing.JRadioButton jRadioButtonCAP7_1;
    private javax.swing.JRadioButton jRadioButtonCAP7_2;
    private javax.swing.JRadioButton jRadioButtonCAP7_3;
    private javax.swing.JRadioButton jRadioButtonCAP7_4;
    private javax.swing.JRadioButton jRadioButtonCAP7_5;
    private javax.swing.JRadioButton jRadioButtonCAP7_6;
    private javax.swing.JRadioButton jRadioButtonCAP7_7;
    private javax.swing.JRadioButton jRadioButtonCAP7_8;
    private javax.swing.JSpinner jSpinnerCAP8;
    private javax.swing.JTabbedPane jTabbedPaneQuestionario;
    private javax.swing.JTextField jTextFieldCAP7_8;
    private javax.swing.JTextField jTextFieldMediaCandidatura;
    private javax.swing.JTextField jTextFieldOutroCAP2Curso;
    // End of variables declaration//GEN-END:variables
}
